# Generated by Django 4.2.7 on 2026-02-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_scrapeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='is_elfsight',
            field=models.BooleanField(default=False),
        ),
    ]
