# Generated by Django 4.2.7 on 2026-02-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0004_scrapeddata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
