# Generated by Django 4.2.7 on 2026-02-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0005_scrapeddata_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='listing_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
