# Generated by Django 4.2.7 on 2026-02-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0006_scrapeddata_listing_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain to blacklist (e.g., birdeye.com, yelp.com)', max_length=255, unique=True)),
                ('category', models.CharField(blank=True, help_text='Category (e.g., Review Sites, Social Media)', max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Why this domain is blacklisted')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable this filter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Domain',
                'verbose_name_plural': 'Blacklisted Domains',
                'ordering': ['category', 'domain'],
            },
        ),
    ]
