# Generated by Django 4.2.7 on 2026-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0007_blacklisteddomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Search engine name (e.g., Google, Bing)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this search engine')),
                ('search_url_template', models.CharField(help_text='URL template with {query} placeholder', max_length=500)),
                ('priority', models.IntegerField(default=1, help_text='Search order (1=highest priority)')),
                ('add_reviews_keyword', models.BooleanField(default=True, help_text="Add 'reviews' to search query")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Engine',
                'verbose_name_plural': 'Search Engines',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
