# Generated by Django 4.2.7 on 2026-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0008_searchengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchengine',
            name='delay_between_requests',
            field=models.FloatField(default=2.0, help_text='Delay in seconds between requests (avoid IP blocking)'),
        ),
        migrations.AddField(
            model_name='searchengine',
            name='max_results',
            field=models.IntegerField(default=10, help_text='Maximum results to fetch per search'),
        ),
    ]
